# project congfiguration
[project_settings]
chromer_driver_path = "C:\\Progra~1\\chromedriver-win64\\chromedriver.exe"
chrome_path = "C:\\Progra~1\\Google\\Chrome\\Application\\chrome.exe"
chrome_data_dir = "C:\\Users\\Ramesh\\Desktop\\chatgpt_selenium\\chrome_data"
batch_size = 30

[folder_config]
input_dir = "C:\\Users\\Ramesh\\Desktop\\source_dir"
output_dir = "C:\\Users\\Ramesh\\Desktop\\dest_dir"
temp_dir = "temp_extract"


[chatgpt_config]
prompt = "You are the invoice detail extract assistant for the company named JATAH WORX INDIA PRIVATE. You should extract the following thiinvoice number, date and name of the person. invoice details will be provided in backticks below. Make sure you don't provide the company name as name of the person. Provide the output only in json format where the key values should be name, invoice_number and date, for the date follow the format mentioned in the square brackets [date-month-year] and for example date value is 19-september-2020."