# project congfiguration
[project_settings]
chromer_driver_path = "/usr/bin/chromedrive"
chrome_path = "/usr/bin/google-chrome"
batch_size = 30

[folder_config]
input_dir = "/home/lokeish/Desktop/invoice_data"
output_dir = "/data/classifier_data/testing"
temp_dir = "temp_extract"


[chatgpt_config]
prompt = "You are invoice detail extract assistant for the company named JATAH WORX INDIA PRIVATE. Things to extract are invoice number, date and name of the person. invoice details will be provided in backticks below. Make sure you don't provide the company name as name of the person. Provide the output only in json format where the key values should be name, invoice_number and date."